apiVersion: apps/v1
kind: Deployment
metadata:
  name: logstash
  labels:
    k8s-app: logstash
spec:
  selector:
    matchLabels:
      k8s-app: logstash
  template:
    metadata:
      labels:
        k8s-app: logstash
    spec:
      containers:
      - name: logstash
        image: docker.elastic.co/logstash/logstash:8.9.2
        env:
        #- name: ELASTICSEARCH_HOST
        #  value: elasticsearch
        #- name: ELASTICSEARCH_PORT
        #  value: "9200"
        #- name: ELASTICSEARCH_USERNAME
        #  value: elastic
        #- name: ELASTICSEARCH_PASSWORD
        #  value: changeme
        #- name: ELASTIC_CLOUD_ID
        #  value:
        #- name: ELASTIC_CLOUD_AUTH
        #  value:
        #resources:
        #  limits:
        #    memory: 200Mi
        #  requests:
        #    cpu: 100m
        #    memory: 100Mi
        volumeMounts:
        - name: config
          mountPath: /usr/share/logstash/config/pipelines.yml
          readOnly: true
          subPath: pipelines.yml
        - name: config
          mountPath: /usr/share/logstash/config/logstash.yml
          readOnly: true
          subPath: logstash.yml
        - name: pipeline-filebeat
          mountPath: /usr/share/logstash/pipeline/filebeat
        #- name: data
        #  mountPath: /usr/share/filebeat/data
        #- name: varlibdockercontainers
        #  mountPath: /var/lib/docker/containers
        #  readOnly: true
        #- name: varlog
        #  mountPath: /var/log
        #  readOnly: true
      volumes:
      - name: config
        configMap:
          defaultMode: 0640
          name: logstash-config
      - name: pipeline-midas
        configMap:
          defaultMode: 0640
          name: logstash-pipeline-filebeat

