apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-pipeline-filebeat
  labels:
    k8s-app: logstash
data:
  filebeat.conf: |-
    input {
      beats {
        port => 5044
      }
    }

    output {
      stdout {
        codec => rubydebug
      }
    }
